version: '3.2'

services:
  gcn_telegram:
    build: Alkousa
    volumes:
      - ./Alkousa/handle:/app/handle:ro
      - ./Alkousa/token:/app/token:ro

  swift_light_curve:
    build: Avakyan
    # Works extremely long with valid objects
    command: ["TEST_TEST_TEST"] # ["GRB 171222A"]

  gcn_discord:
    build: Balakin
    volumes:
      - ./Balakin/discord_apikey:/app/discord_apikey:ro

  sn_peak:
    build: Fedotieva
    command: ["SN2017eye"]

  ads_sai:
    build: Grishin
    env_file: ./Grishin/secret.env

  ztf_color:
    build: Podzolkova

  navigator:
    build: Strakhov
    ports:
      - "8001:8888"

  martian_news:
    build: Tavleev
    ports:
      - "8002:8888"
    env_file: ./Tavleev/secret.env

  kgo_weather_darksky:
    build: Zheltoukhov
    volumes:
      - ./Zheltoukhov/weather.dat:/app/weather.dat
      - ./Zheltoukhov/key.txt:/app/key.txt:ro
