name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup secret files
      run: |
        cat "${{ secrets.Alkousa_handle }}" > Alkousa/handle
        cat "${{ secrets.Alkousa_token }}" > Alkousa/token
        cat "${{ secrets.Balakin_discord_apikey }}" > Balakin/discord_apikey
        cat "${{ secrets.Grishin_secret_env }}" > Grishin/secret.env
        cat "${{ secrets.Tavleev_secret_env }}" > Tavleev/secret.env
        cat "${{ secrets.Zheltoukhov_key_txt }}" > Zheltoukhov/key.txt
    - name: Build containers
      run: docker-compose build
